.TH "Cell" 3 "Sun May 8 2022" "DNATool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DirectionMat\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBc0\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBc1\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBc2\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBc3\fP: 2"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t Cell::c0"

.SS "uint8_t Cell::c1"

.SS "uint8_t Cell::c2"

.SS "uint8_t Cell::c3"


.SH "Author"
.PP 
Generated automatically by Doxygen for DNATool from the source code\&.
