.TH "DirectionMat.h" 3 "Sun May 8 2022" "DNATool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectionMat.h \- Implements 2 bit-size matrix cells\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <random>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCell\fP"
.br
.ti -1c
.RI "class \fBDirectionMat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements 2 bit-size matrix cells\&. 


.PP
\fBAuthors\fP
.RS 4
DALZOTTO, Rafael; HEIR, Alejandro - Grupo 7 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-08
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 - 22\&.08 EDA - ITBA 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for DNATool from the source code\&.
