.TH "GBReader.cpp" 3 "Sun May 8 2022" "DNATool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GBReader.cpp \- Sequence extractor for GenBank-like files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'GBReader\&.h'\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBnotIsACGT\fP (char c)"
.br
.RI "Checks if a given character is not 'a', 'c', 'g' or 't'\&. "
.ti -1c
.RI "bool \fBgetSequence\fP (string &output, istream &file)"
.br
.RI "Extracts an acgt-like string from a GenBank file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sequence extractor for GenBank-like files\&. 


.PP
\fBAuthors\fP
.RS 4
DALZOTTO, Rafael; HEIR, Alejandro - Grupo 7 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-08
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 - 22\&.08 EDA - ITBA 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool getSequence (string & output, istream & file)"

.PP
Extracts an acgt-like string from a GenBank file\&. 
.PP
\fBParameters\fP
.RS 4
\fIoutput\fP String to store the acgt sequence 
.br
\fIfile\fP ifstream file handler\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true Success 
.PP
false Failure 
.RE
.PP

.SS "bool notIsACGT (char c)"

.PP
Checks if a given character is not 'a', 'c', 'g' or 't'\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true It's not 
.PP
false It is 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for DNATool from the source code\&.
