.TH "main_test.cpp" 3 "Sun May 8 2022" "DNATool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_test.cpp \- Tests for the genetic sequence aligner\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <array>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'GBReader\&.h'\fP
.br
\fC#include 'Aligner\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtestMatInit\fP (\fBDirectionMat\fP *&mat, const string &s1, const string &s2, \fBDirectionMat\fP &expectedMat)"
.br
.ti -1c
.RI "bool \fBtestFillMat\fP (\fBDirectionMat\fP *mat, const string &s1, const string &s2, int32_t expectedScore, \fBDirectionMat\fP &expectedMat)"
.br
.ti -1c
.RI "bool \fBtestAlignment\fP (\fBDirectionMat\fP *mat, const string &s1, const string &s2, array< string, 3 > &expectedAlignment)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests for the genetic sequence aligner\&. 


.PP
\fBAuthors\fP
.RS 4
DALZOTTO, Rafael; HEIR, Alejandro - Grupo 7 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-05-08
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 - 22\&.08 EDA - ITBA 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "bool testAlignment (\fBDirectionMat\fP * mat, const string & s1, const string & s2, array< string, 3 > & expectedAlignment)"

.SS "bool testFillMat (\fBDirectionMat\fP * mat, const string & s1, const string & s2, int32_t expectedScore, \fBDirectionMat\fP & expectedMat)"

.SS "bool testMatInit (\fBDirectionMat\fP *& mat, const string & s1, const string & s2, \fBDirectionMat\fP & expectedMat)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DNATool from the source code\&.
